name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build-vote:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        uses: docker/login-action@v1.12.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: # optional
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }} # optional
          # Specifies whether the given registry is ECR (auto, true or false)
          # ecr: # optional, default is auto
          # Log out from the Docker registry at the end of a job
          # logout: # optional, default is true
      - name: Checkout commit to work around https://github.com/docker/build-push-action/issues/541
        uses: actions/checkout@v2
      - name: Build and push Docker image
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@1814d3dfb36d6f84174e61f4a4b05bd84089a4b9
        uses: docker/build-push-action@master
        with:
          # List of extra privileged entitlement (e.g., network.host,security.insecure)
          # allow: # optional
          # List of build-time variables
          # build-args: # optional
          # Builder instance
          # builder: # optional
          # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
          # cache-from: # optional
          # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
          # cache-to: # optional
          # Optional parent cgroup for the container used in the build
          # cgroup-parent: # optional
          # Build's context is the set of files located in the specified PATH or URL
          context: ./vote # optional
          # Path to the Dockerfile
          # file: # optional
          # List of metadata for an image
          # labels: # optional
          # Load is a shorthand for --output=type=docker
          # load: # optional, default is false
          # Set the networking mode for the RUN instructions during build
          # network: # optional
          # Do not use cache when building the image
          # no-cache: # optional, default is false
          # List of output destinations (format: type=local,dest=path)
          # outputs: # optional
          # List of target platforms for build
          # platforms: # optional
          # Always attempt to pull a newer version of the image
          # pull: # optional, default is false
          # Push is a shorthand for --output=type=registry
          push: true # optional, default is false
          # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
          # secrets: # optional
          # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
          # secret-files: # optional
          # Size of /dev/shm (e.g., 2g)
          # shm-size: # optional
          # List of SSH agent socket or keys to expose to the build
          # ssh: # optional
          # List of tags
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}-vote:latest # optional
          # Sets the target stage to build
          # target: # optional
          # Ulimit options (e.g., nofile=1024:1024)
          # ulimit: # optional
          # GitHub Token used to authenticate against a repository for Git context
          # github-token: # optional, default is ${{ github.token }}
      - name: Docker Hub Description
        # You may pin to the exact commit or the version.
        # uses: peter-evans/dockerhub-description@616d1b63e806b630b975af3b4fe3304307b20f40
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          # Docker Hub username
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Docker Hub password
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Docker Hub repository in the format `<namespace>/<name>` Default: `github.repository`
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}-vote
          # Docker Hub repository short description Input exceeding 100 characters will be truncated
          # short-description: # optional
          # Path to the repository readme Default: `./README.md`
          # readme-filepath: # optional
